---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: weather-prd
spec:
  type: NodePort
  selector:
    app: weather-server
  ports:
    - nodePort: 30121
      port: 8080
      targetPort: 8080