---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-server
  namespace: weather-dev
spec:
  selector:
    matchLabels:
      app: weather-server
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-server
    spec:
      containers:
      - name: weather-server
        image:
        env:
        - name: ELASTIC_HOST
          valueFrom:
            configMapKeyRef:
              name: weather-config-dev
              key: elastic-host
        - name: WEATHER_ENV
          valueFrom:
            configMapKeyRef:
              name: weather-config-dev
              key: weather-env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: weather-config-dev
              key: log-level
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        imagePullPolicy: Always
      imagePullSecrets:
      - name: docker-hub-pull-secret