@startuml
'https://plantuml.com/class-diagram

interface MAIN {
    main(): int
}

interface common.Client {
    +Do(req *http.Request): (*http.Response, error)
}

interface weather.WeatherService {
    +Save(model.WeatherRecord): error
}

class weather.ElasticImpl {
    ~common.Client
    +Save(model.WeatherRecord): error
}

MAIN --> weather
MAIN --> common
WeatherService <-- ElasticImpl


@enduml