@startuml
'https://plantuml.com/deployment-diagram

actor User
control Firewall
control Proxy
node WeatherServer #Orange
node WeatherNode {
    component SenseHAT
}
database Elasticsearch
rectangle Kibana

User <--> Proxy
Proxy <--> Firewall
Firewall <--> Kibana
WeatherNode --> WeatherServer
WeatherServer --> Elasticsearch
Elasticsearch <--> Kibana

@enduml